### ISSUE TITLE
What does this mod do specifically?

### ISSUE THREAD

**Issue by Azzinoth224** [deltanedas/routorio-old#17]
There are so many mindustry mods with insufficient descriptions. Why?

**Comment by deltanedas** [comment]
it should be obvious from the name, icon or preview image

**Comment by Azzinoth224** [comment]
I can see that it has something to do with routers, but not more. Does it add different routers? What do they do? Or does it change the behaviour of vanilla routers? Maybe it makes it so that routers don't send items backwards anymore? If I take the words "router expansion" literally, I guess it just makes routers bigger?
