### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Stavinair** [deltanedas/routorio-old#18]
Unsure if it's my device or the code.

Mindustry has crashed. How unfortunate.
Version: release build 121.2
OS: Linux x32
Java Version: 0
Java Architecture: null
1 Mods: routorio:2.36.0

> ArcRuntime: 'rhino.EcmaError: ReferenceError: "LocalDate" is not defined. (xmas#4)'
AssetManager.handleTaskError: 670
AssetManager.update: 442
AssetManager.update: 465
ClientLauncher.update: 137
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1535
GLSurfaceView$GLThread.run: 1240
> EcmaError: 'ReferenceError: "LocalDate" is not defined. (xmas#4)'
ScriptRuntime.constructError: 3955
ScriptRuntime.constructError: 3935
ScriptRuntime.notFoundError: 4012
ScriptRuntime.name: 1774
xmas_29._c_isDec_1: 4
xmas_29.call: -1
OptRuntime.callName0: 61
xmas_29._c_anonymous_7: 48
xmas_29.call: -1
Context.lambda$call$0: 515
-$$Lambda$Context$cFPn5DXqStb0JnJKYei-AlpJVlo.run: -1
Context.call: 524
Context.call: 515
JavaAdapter.callMethod: 549
adapter15.ready: -1
MemberBox.invoke: 105
NativeJavaMethod.call: 205
OptRuntime.callProp0: 71
xmas_29._c_anonymous_2: 12
xmas_29.call: -1
ContextFactory.doTopCall: 346
ScriptRuntime.doTopCall: 3303
xmas_29.call: -1
Context.lambda$call$0: 515
-$$Lambda$Context$cFPn5DXqStb0JnJKYei-AlpJVlo.run: -1
Context.call: 524
Context.call: 515
JavaAdapter.callMethod: 549
adapter15.load: -1
Mods.lambda$loadSync$7$Mods: 174
-$$Lambda$Mods$F1LFTbW8_n2RhDLDkIMceaeAzmw.get: -1
Seq.each: 200
Mods.loadSync: 172
AssetManager$2.loadSync: 358
AssetLoadingTask.handleAsyncLoader: 109
AssetLoadingTask.update: 74
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 137
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1535
GLSurfaceView$GLThread.run: 1240

**Comment by deltanedas** [comment]
routorio requires java 8
on dpkg-based systems: `apt install openjdk-8-jre-headless`
