### ISSUE TITLE
Clear Router Crash

### ISSUE THREAD

**Issue by pswsm** [deltanedas/routorio-old#21]
**Platform**:
Arch Linux x86_64

**Mindustry Version**:
stable 122.1

**Routorio Version**: *the number please*
"latest"

**Describe the issue**:
Clear Router makes the game crash when placed, or a map with it is loaded.

**Steps to reproduce, including save file if non trivial**
1. Place a Clear Router
2. Crash

**(Crash) logs, if relevant**
https://pastebin.com/GJAtxsTU

**Comment by deltanedas** [comment]
not "latest", update
