### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rodrigolitzius** [deltanedas/routorio-old#22]
**Platform**:
Android

**Mindustry Version**:
Read the crash log

**Routorio Version**: *the number please*
latest (I got it from mod browser)

**Describe the issue**:
Did u read the title?

**Steps to reproduce, including save file if non trivial**
1. Yes

**(Crash) logs, if relevant**
(
Mindustry has crashed. How unfortunate.
Version: release build 122.1
OS: Linux x32
Java Version: 0
Java Architecture: null
8 Mods: dev-mode:2.3.2, routorio:2.36.0, ui-lib:2.16.4, anuke-logic:1.6.1, bugdustry:1, ldb:1.1.0, pictologic:1.5.2, rtfm:2.14.1

> ArcRuntime: 'rhino.EcmaError: ReferenceError: "LocalDate" is not defined. (xmas#4)'
AssetManager.handleTaskError: 670
AssetManager.update: 442
AssetManager.update: 465
ClientLauncher.update: 137
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259
> EcmaError: 'ReferenceError: "LocalDate" is not defined. (xmas#4)'
ScriptRuntime.constructError: 3955
ScriptRuntime.constructError: 3935
ScriptRuntime.notFoundError: 4012
ScriptRuntime.name: 1774
xmas_33._c_isDec_1: 4
xmas_33.call: -1
OptRuntime.callName0: 61
xmas_33._c_anonymous_7: 48
xmas_33.call: -1
Context.lambda$call$0: 515
-$$Lambda$Context$cFPn5DXqStb0JnJKYei-AlpJVlo.run: -1
Context.call: 524
Context.call: 515
JavaAdapter.callMethod: 549
adapter15.ready: -1
MemberBox.invoke: 105
NativeJavaMethod.call: 205
OptRuntime.callProp0: 71
xmas_33._c_anonymous_2: 12
xmas_33.call: -1
ContextFactory.doTopCall: 346
ScriptRuntime.doTopCall: 3303
xmas_33.call: -1
Context.lambda$call$0: 515
-$$Lambda$Context$cFPn5DXqStb0JnJKYei-AlpJVlo.run: -1
Context.call: 524
Context.call: 515
JavaAdapter.callMethod: 549
adapter15.load: -1
Mods.lambda$loadSync$7$Mods: 174
-$$Lambda$Mods$F1LFTbW8_n2RhDLDkIMceaeAzmw.get: -1
Seq.each: 200
Mods.loadSync: 172
AssetManager$2.loadSync: 358
AssetLoadingTask.handleAsyncLoader: 109
AssetLoadingTask.update: 74
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 137
AndroidGraphics.onDrawFrame: 424
GLSurfaceView$GLThread.guardedRun: 1548
GLSurfaceView$GLThread.run: 1259
)

**Comment by SorterBoi** [comment]
Bruh

**Comment by rodrigolitzius** [comment]
The game crash when i start it

**Comment by deltanedas** [comment]
you need java 8
the xmas router uses localdate, you can comment it all out til next year
