### ISSUE TITLE
Clear Router crash

### ISSUE THREAD

**Issue by AlbinoGeek** [deltanedas/routorio-old#24]
**Platform**:
Android Q

**Mindustry Version**:
Release 1.2.2.1

**Routorio Version**:
`master` v2.36.0

**Describe the issue**:
Crash to launcher

**Steps to reproduce, including save file if non trivial**
1. Go to any Map
2. Place a Clear Router

**(Crash) logs, if relevant**
`adb logs` showed no entries for Mindustry.

---

Yes, I saw #22 #21 #20 #18 ... this is on the latest version however.

**Comment by deltanedas** [comment]
@AlbinoGeek adb sucks, logs are stored on your device in /sdcard/Android/data/io.anuke.mindustry/files/crashes

**Comment by deltanedas** [comment]
assuming the crash cause is the same, install java 8
of course if android wasnt a monolithic piece of shit you could just `apt install openjdk-8-jre-headless` and go on your way

**Comment by deltanedas** [comment]
ok
