### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AlbinoGeek** [deltanedas/routorio-old#25]
It would be nice to have comparable specifications for the routers, to know when to use them.

Specifically, it's hard to tell which is the fastest:

- Half Router
- Invert Router
- Mini Distribute (Replaces Vanilla Distribute)
- Router (Vanilla)

---

Additionally, so far, the following router all act the same (not a discernible difference):

- Explode Router
- Invert Router
- Mini Distribute
- Router (Vanilla)

---

While I can easily enough go through the source in `scripts/` and figure out what the routers do, it's not immediately obvious to the user, and since these routers don't have pages within `RTFM`, this repository has a very clean `README.md`, no `docs/` folder, and no Wiki... there's nowhere else to get that information.

**Comment by deltanedas** [comment]
> Additionally, so far, the following router all act the same (not a discernible difference):

> Explode Router

thank you for being a good player

> Invert Router

read the description, it's a conveyor

router speeds are all the same, titanium double router being the exception however it forces router chaining without logic, so it's usually slower in practise.
adding manpage about it
