### ISSUE TITLE
Ubuntium Router gives beryllium without researching it

### ISSUE THREAD

**Issue by AlbinoGeek** [deltanedas/routorio-old#26]
**Platform**:
Android Q

**Mindustry Version**:
Release 1.2.2.1

**Routorio Version**:
`master` v2.36.0

**Describe the issue**:
You can (ab)use the Ubuntium Router to produce beryllium in place of something inexpensive (like Copper) into an unlimited source of a resource you don't even have yet.

**Steps to reproduce, including save file if non trivial**
1. Unlock Ubuntium Router (but not beryllium)
2. Go to any Map
3. Place Ubuntium Router

**Comment by deltanedas** [comment]
ok

**Comment by deltanedas** [comment]
fixed
