### ISSUE TITLE
You can't sort beryllium

### ISSUE THREAD

**Issue by AlbinoGeek** [deltanedas/routorio-old#27]
**Platform**:
Android Q

**Mindustry Version**:
Release 1.2.2.1

**Routorio Version**:
`master` v2.36.0

**Describe the issue**:
![image](https://user-images.githubusercontent.com/1910461/105436417-018c3800-5c14-11eb-91ba-71f66973960d.png)

**Steps to reproduce, including save file if non trivial**
1. Unlock everything in routerio
2. Open any Map
3. Place a Sorter, Inverted Sorter, etc
4. Try to sort beryllium

**Comment by deltanedas** [comment]
beryllium extends item so sorter hates it, wontfix
