### ISSUE TITLE
Multirouter no texture/ functionality

### ISSUE THREAD

**Issue by oguh43** [deltanedas/routorio-old#29]
**Platform**:
win10 x64

**Mindustry Version**:
stable 123.1

**Routorio Version**: *the number please*
2.36.0
**Describe the issue**:
Multirouter no texture/ functionality

**Comment by oguh43** [comment]
also applies to routoid liquefactor

**Comment by deltanedas** [comment]
no texture yes
no functionality no
it kills poly
