### ISSUE TITLE
armored router

### ISSUE THREAD

**Issue by lokyinng** [deltanedas/routorio-old#38]
**Name**:
armored router

**Description/Background**:
router but aromored

**Mechanics**:
heavy more health than router

**Comment by deltanedas** [comment]
exist

**Comment by Volas171** [comment]
4 minutes ago

**Comment by Volas171** [comment]
![imagen](https://user-images.githubusercontent.com/60143910/143793027-9ac773d3-561b-4b66-bb7b-a20eaf35b26e.png)
wonder why it got into my mail lmao
