### ISSUE TITLE
xmas router goes clash

### ISSUE THREAD

**Issue by lokyinng** [deltanedas/routorio-old#40]
**Platform**:
Debian sid amd64

**Mindustry Version**
latest v7

**Routorio Version**: *the number please*
"latest"

**Describe the issue**:
xmas router clash the game

**Steps to reproduce, including save file if non trivial**
1. use routorio mod
2. place a Xmas router if you ever need it
3. probably delete it
4. wait, wait and wait
5. probably place an alien router
6. more waiting
7. the game has clashed

**(Crash) logs, if relevant**
no

**Comment by deltanedas** [comment]
clash of clans
