### ISSUE TITLE
sprouter adn christmas router dont like being placed

### ISSUE THREAD

**Issue by TheGamer1002** [deltanedas/routorio-old#44]
**Platform**:
windows 11 build 69420

**Mindustry Version**:
pre-alpha 135

**Routorio Version**: *the number please*
"latest" (theres no number lmao

**Describe the issue**:
they dont want to be placed

**Steps to reproduce, including save file if non trivial**
1. click router
2. y u no place router!

**(Crash) logs, if relevant**

**Comment by deltanedas** [comment]
sprouter can only be placed on dirt
christmas routers cannot be bought in january
