### ISSUE TITLE
PLEASE

### ISSUE THREAD

**Issue by ViniciusLopes7** [deltanedas/routorio-old#6]
[Mod Itens.zip](https://github.com/DeltaNedas/routorio/files/5179002/Mod.Itens.zip)
Could you try to make your mod clear router work on my mod? Please

If I wrote it wrong and because I don't speak English
@DeltaNedas

**Comment by deltanedas** [comment]
Since you copy pasted example mod I have no idea what to look for.
I don't even know what the issue is.

**Comment by ViniciusLopes7** [comment]
The Clear-router does not work only appears on the tech-tree and is on the floor, but does not transport the items.
