### ISSUE TITLE
fusion router crashes

### ISSUE THREAD

**Issue by USMP-lancer** [deltanedas/routorio-old#9]
probably a broken script tbh

**Comment by USMP-lancer** [comment]
its not a mismatch of versions, just made sure of that

**Comment by USMP-lancer** [comment]
[crash_1602377624526.txt](https://github.com/DeltaNedas/routorio/files/5360442/crash_1602377624526.txt)
crash report

**Comment by USMP-lancer** [comment]
btw classicified is just sprite overrides

**Comment by deltanedas** [comment]
i know, read the comment
i'm currently working on fusion router
